language: java
# for an overview see https://docs.travis-ci.com/user/reference/overview/
sudo: false
dist: trusty

cache:
    directories:
        - $HOME/.m2

jobs:
    include:  
        - name: "JDK openjdk8 + coverage"
          jdk: openjdk8
          script: cd ./jpa && mvn clean verify 
          after_success:
              - cd ./jpa && mvn clean test jacoco:report coveralls:report

branches:
    only:
        - master
        - develop