language: java
# for an overview see https://docs.travis-ci.com/user/reference/overview/
sudo: false
dist: trusty
jdk:
    - oraclejdk8
    - oraclejdk9
cache:
  directories:
    - $HOME/.m2/repository

branches:
  only:
  - master
  - develop
