language: java
# for an overview see https://docs.travis-ci.com/user/reference/overview/
sudo: false
dist: trusty
jdk:
    - oraclejdk8
    - oraclejdk9
    - openjdk8
cache:
  directories:
    - $HOME/.m2/repository
script:
    - cd jpa && mvn clean verify
branches:
  only:
  - master
  - develop

  after_success:
  - mvn clean test jacoco:report coveralls:report